on:
  workflow_dispatch:


jobs:
  jobs_1:
    strategy:
      fail-fast: false
      max-parallel: 3
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        node_version: [18.x, 20.x]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/setup-node@v3.6.0
        with:
          node-version: ${{ matrix.node_version }}