on: 
  workflow_dispatch:


jobs:
  job_1:
    runs-on: ubuntu-latest

    steps:
      - run: |
          npm install
          npm test
          npm run lint
          npm run build
        working-directory: ./temp
        shell: bash   # pwsh | bash | python | cmd | sh |powershell
      
      - run: print %ENV
        shell: perl {0}
